// Generated by gencpp from file mav_offboard/GenTrajOnline.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_GENTRAJONLINE_H
#define MAV_OFFBOARD_MESSAGE_GENTRAJONLINE_H

#include <ros/service_traits.h>


#include <mav_offboard/GenTrajOnlineRequest.h>
#include <mav_offboard/GenTrajOnlineResponse.h>


namespace mav_offboard
{

struct GenTrajOnline
{

typedef GenTrajOnlineRequest Request;
typedef GenTrajOnlineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenTrajOnline
} // namespace mav_offboard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_offboard::GenTrajOnline > {
  static const char* value()
  {
    return "1c8daf56fea4f669979846d8a40908f8";
  }

  static const char* value(const ::mav_offboard::GenTrajOnline&) { return value(); }
};

template<>
struct DataType< ::mav_offboard::GenTrajOnline > {
  static const char* value()
  {
    return "mav_offboard/GenTrajOnline";
  }

  static const char* value(const ::mav_offboard::GenTrajOnline&) { return value(); }
};


// service_traits::MD5Sum< ::mav_offboard::GenTrajOnlineRequest> should match
// service_traits::MD5Sum< ::mav_offboard::GenTrajOnline >
template<>
struct MD5Sum< ::mav_offboard::GenTrajOnlineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::GenTrajOnline >::value();
  }
  static const char* value(const ::mav_offboard::GenTrajOnlineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::GenTrajOnlineRequest> should match
// service_traits::DataType< ::mav_offboard::GenTrajOnline >
template<>
struct DataType< ::mav_offboard::GenTrajOnlineRequest>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::GenTrajOnline >::value();
  }
  static const char* value(const ::mav_offboard::GenTrajOnlineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_offboard::GenTrajOnlineResponse> should match
// service_traits::MD5Sum< ::mav_offboard::GenTrajOnline >
template<>
struct MD5Sum< ::mav_offboard::GenTrajOnlineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::GenTrajOnline >::value();
  }
  static const char* value(const ::mav_offboard::GenTrajOnlineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::GenTrajOnlineResponse> should match
// service_traits::DataType< ::mav_offboard::GenTrajOnline >
template<>
struct DataType< ::mav_offboard::GenTrajOnlineResponse>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::GenTrajOnline >::value();
  }
  static const char* value(const ::mav_offboard::GenTrajOnlineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_GENTRAJONLINE_H
