// Generated by gencpp from file mav_offboard/GenTrajOnlineRequest.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_GENTRAJONLINEREQUEST_H
#define MAV_OFFBOARD_MESSAGE_GENTRAJONLINEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/TwistStamped.h>

namespace mav_offboard
{
template <class ContainerAllocator>
struct GenTrajOnlineRequest_
{
  typedef GenTrajOnlineRequest_<ContainerAllocator> Type;

  GenTrajOnlineRequest_()
    : targPoint()
    , pose()
    , twist()
    , isUpdateState(false)  {
    }
  GenTrajOnlineRequest_(const ContainerAllocator& _alloc)
    : targPoint(_alloc)
    , pose(_alloc)
    , twist(_alloc)
    , isUpdateState(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _targPoint_type;
  _targPoint_type targPoint;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef uint8_t _isUpdateState_type;
  _isUpdateState_type isUpdateState;





  typedef boost::shared_ptr< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenTrajOnlineRequest_

typedef ::mav_offboard::GenTrajOnlineRequest_<std::allocator<void> > GenTrajOnlineRequest;

typedef boost::shared_ptr< ::mav_offboard::GenTrajOnlineRequest > GenTrajOnlineRequestPtr;
typedef boost::shared_ptr< ::mav_offboard::GenTrajOnlineRequest const> GenTrajOnlineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator2> & rhs)
{
  return lhs.targPoint == rhs.targPoint &&
    lhs.pose == rhs.pose &&
    lhs.twist == rhs.twist &&
    lhs.isUpdateState == rhs.isUpdateState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_offboard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7be0038aa37973ee7d8786bd8a24adf";
  }

  static const char* value(const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7be0038aa37973eULL;
  static const uint64_t static_value2 = 0xe7d8786bd8a24adfULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_offboard/GenTrajOnlineRequest";
  }

  static const char* value(const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped targPoint\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/TwistStamped twist\n"
"bool isUpdateState\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistStamped\n"
"# A twist with reference coordinate frame and timestamp\n"
"Header header\n"
"Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targPoint);
      stream.next(m.pose);
      stream.next(m.twist);
      stream.next(m.isUpdateState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenTrajOnlineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_offboard::GenTrajOnlineRequest_<ContainerAllocator>& v)
  {
    s << indent << "targPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.targPoint);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "isUpdateState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isUpdateState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_GENTRAJONLINEREQUEST_H
