// Generated by gencpp from file mav_offboard/IintWayPointsRequest.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_IINTWAYPOINTSREQUEST_H
#define MAV_OFFBOARD_MESSAGE_IINTWAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace mav_offboard
{
template <class ContainerAllocator>
struct IintWayPointsRequest_
{
  typedef IintWayPointsRequest_<ContainerAllocator> Type;

  IintWayPointsRequest_()
    : initWayPoints()  {
    }
  IintWayPointsRequest_(const ContainerAllocator& _alloc)
    : initWayPoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _initWayPoints_type;
  _initWayPoints_type initWayPoints;





  typedef boost::shared_ptr< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IintWayPointsRequest_

typedef ::mav_offboard::IintWayPointsRequest_<std::allocator<void> > IintWayPointsRequest;

typedef boost::shared_ptr< ::mav_offboard::IintWayPointsRequest > IintWayPointsRequestPtr;
typedef boost::shared_ptr< ::mav_offboard::IintWayPointsRequest const> IintWayPointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.initWayPoints == rhs.initWayPoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_offboard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5aeaf576c4b1e16ec432ad81014ebfb";
  }

  static const char* value(const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5aeaf576c4b1e16ULL;
  static const uint64_t static_value2 = 0xec432ad81014ebfbULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_offboard/IintWayPointsRequest";
  }

  static const char* value(const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] initWayPoints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.initWayPoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IintWayPointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_offboard::IintWayPointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_offboard::IintWayPointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "initWayPoints[]" << std::endl;
    for (size_t i = 0; i < v.initWayPoints.size(); ++i)
    {
      s << indent << "  initWayPoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.initWayPoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_IINTWAYPOINTSREQUEST_H
