// Generated by gencpp from file mav_offboard/SetMavOffbCtlType.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_SETMAVOFFBCTLTYPE_H
#define MAV_OFFBOARD_MESSAGE_SETMAVOFFBCTLTYPE_H

#include <ros/service_traits.h>


#include <mav_offboard/SetMavOffbCtlTypeRequest.h>
#include <mav_offboard/SetMavOffbCtlTypeResponse.h>


namespace mav_offboard
{

struct SetMavOffbCtlType
{

typedef SetMavOffbCtlTypeRequest Request;
typedef SetMavOffbCtlTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMavOffbCtlType
} // namespace mav_offboard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_offboard::SetMavOffbCtlType > {
  static const char* value()
  {
    return "ba3bb96f001193382c990776aa0640ca";
  }

  static const char* value(const ::mav_offboard::SetMavOffbCtlType&) { return value(); }
};

template<>
struct DataType< ::mav_offboard::SetMavOffbCtlType > {
  static const char* value()
  {
    return "mav_offboard/SetMavOffbCtlType";
  }

  static const char* value(const ::mav_offboard::SetMavOffbCtlType&) { return value(); }
};


// service_traits::MD5Sum< ::mav_offboard::SetMavOffbCtlTypeRequest> should match
// service_traits::MD5Sum< ::mav_offboard::SetMavOffbCtlType >
template<>
struct MD5Sum< ::mav_offboard::SetMavOffbCtlTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::SetMavOffbCtlType >::value();
  }
  static const char* value(const ::mav_offboard::SetMavOffbCtlTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::SetMavOffbCtlTypeRequest> should match
// service_traits::DataType< ::mav_offboard::SetMavOffbCtlType >
template<>
struct DataType< ::mav_offboard::SetMavOffbCtlTypeRequest>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::SetMavOffbCtlType >::value();
  }
  static const char* value(const ::mav_offboard::SetMavOffbCtlTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_offboard::SetMavOffbCtlTypeResponse> should match
// service_traits::MD5Sum< ::mav_offboard::SetMavOffbCtlType >
template<>
struct MD5Sum< ::mav_offboard::SetMavOffbCtlTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::SetMavOffbCtlType >::value();
  }
  static const char* value(const ::mav_offboard::SetMavOffbCtlTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::SetMavOffbCtlTypeResponse> should match
// service_traits::DataType< ::mav_offboard::SetMavOffbCtlType >
template<>
struct DataType< ::mav_offboard::SetMavOffbCtlTypeResponse>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::SetMavOffbCtlType >::value();
  }
  static const char* value(const ::mav_offboard::SetMavOffbCtlTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_SETMAVOFFBCTLTYPE_H
