// Generated by gencpp from file mav_offboard/SetTargPointRequest.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_SETTARGPOINTREQUEST_H
#define MAV_OFFBOARD_MESSAGE_SETTARGPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace mav_offboard
{
template <class ContainerAllocator>
struct SetTargPointRequest_
{
  typedef SetTargPointRequest_<ContainerAllocator> Type;

  SetTargPointRequest_()
    : targPoint()  {
    }
  SetTargPointRequest_(const ContainerAllocator& _alloc)
    : targPoint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _targPoint_type;
  _targPoint_type targPoint;





  typedef boost::shared_ptr< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargPointRequest_

typedef ::mav_offboard::SetTargPointRequest_<std::allocator<void> > SetTargPointRequest;

typedef boost::shared_ptr< ::mav_offboard::SetTargPointRequest > SetTargPointRequestPtr;
typedef boost::shared_ptr< ::mav_offboard::SetTargPointRequest const> SetTargPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_offboard::SetTargPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_offboard::SetTargPointRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::SetTargPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.targPoint == rhs.targPoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_offboard::SetTargPointRequest_<ContainerAllocator1> & lhs, const ::mav_offboard::SetTargPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_offboard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07f9d81e02916a6fb0e9369f3eaa2144";
  }

  static const char* value(const ::mav_offboard::SetTargPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07f9d81e02916a6fULL;
  static const uint64_t static_value2 = 0xb0e9369f3eaa2144ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_offboard/SetTargPointRequest";
  }

  static const char* value(const ::mav_offboard::SetTargPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped targPoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mav_offboard::SetTargPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targPoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_offboard::SetTargPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_offboard::SetTargPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "targPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.targPoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_SETTARGPOINTREQUEST_H
