// Generated by gencpp from file mav_offboard/SetTargPoint.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_SETTARGPOINT_H
#define MAV_OFFBOARD_MESSAGE_SETTARGPOINT_H

#include <ros/service_traits.h>


#include <mav_offboard/SetTargPointRequest.h>
#include <mav_offboard/SetTargPointResponse.h>


namespace mav_offboard
{

struct SetTargPoint
{

typedef SetTargPointRequest Request;
typedef SetTargPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargPoint
} // namespace mav_offboard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_offboard::SetTargPoint > {
  static const char* value()
  {
    return "54e4e0134b6e5544072e07794fab0b97";
  }

  static const char* value(const ::mav_offboard::SetTargPoint&) { return value(); }
};

template<>
struct DataType< ::mav_offboard::SetTargPoint > {
  static const char* value()
  {
    return "mav_offboard/SetTargPoint";
  }

  static const char* value(const ::mav_offboard::SetTargPoint&) { return value(); }
};


// service_traits::MD5Sum< ::mav_offboard::SetTargPointRequest> should match
// service_traits::MD5Sum< ::mav_offboard::SetTargPoint >
template<>
struct MD5Sum< ::mav_offboard::SetTargPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::SetTargPoint >::value();
  }
  static const char* value(const ::mav_offboard::SetTargPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::SetTargPointRequest> should match
// service_traits::DataType< ::mav_offboard::SetTargPoint >
template<>
struct DataType< ::mav_offboard::SetTargPointRequest>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::SetTargPoint >::value();
  }
  static const char* value(const ::mav_offboard::SetTargPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_offboard::SetTargPointResponse> should match
// service_traits::MD5Sum< ::mav_offboard::SetTargPoint >
template<>
struct MD5Sum< ::mav_offboard::SetTargPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::SetTargPoint >::value();
  }
  static const char* value(const ::mav_offboard::SetTargPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::SetTargPointResponse> should match
// service_traits::DataType< ::mav_offboard::SetTargPoint >
template<>
struct DataType< ::mav_offboard::SetTargPointResponse>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::SetTargPoint >::value();
  }
  static const char* value(const ::mav_offboard::SetTargPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_SETTARGPOINT_H
