// Generated by gencpp from file mav_offboard/UpdateBoundOnline.msg
// DO NOT EDIT!


#ifndef MAV_OFFBOARD_MESSAGE_UPDATEBOUNDONLINE_H
#define MAV_OFFBOARD_MESSAGE_UPDATEBOUNDONLINE_H

#include <ros/service_traits.h>


#include <mav_offboard/UpdateBoundOnlineRequest.h>
#include <mav_offboard/UpdateBoundOnlineResponse.h>


namespace mav_offboard
{

struct UpdateBoundOnline
{

typedef UpdateBoundOnlineRequest Request;
typedef UpdateBoundOnlineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateBoundOnline
} // namespace mav_offboard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_offboard::UpdateBoundOnline > {
  static const char* value()
  {
    return "b63d0873a52c6e04efd40342ee8fed38";
  }

  static const char* value(const ::mav_offboard::UpdateBoundOnline&) { return value(); }
};

template<>
struct DataType< ::mav_offboard::UpdateBoundOnline > {
  static const char* value()
  {
    return "mav_offboard/UpdateBoundOnline";
  }

  static const char* value(const ::mav_offboard::UpdateBoundOnline&) { return value(); }
};


// service_traits::MD5Sum< ::mav_offboard::UpdateBoundOnlineRequest> should match
// service_traits::MD5Sum< ::mav_offboard::UpdateBoundOnline >
template<>
struct MD5Sum< ::mav_offboard::UpdateBoundOnlineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::UpdateBoundOnline >::value();
  }
  static const char* value(const ::mav_offboard::UpdateBoundOnlineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::UpdateBoundOnlineRequest> should match
// service_traits::DataType< ::mav_offboard::UpdateBoundOnline >
template<>
struct DataType< ::mav_offboard::UpdateBoundOnlineRequest>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::UpdateBoundOnline >::value();
  }
  static const char* value(const ::mav_offboard::UpdateBoundOnlineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_offboard::UpdateBoundOnlineResponse> should match
// service_traits::MD5Sum< ::mav_offboard::UpdateBoundOnline >
template<>
struct MD5Sum< ::mav_offboard::UpdateBoundOnlineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_offboard::UpdateBoundOnline >::value();
  }
  static const char* value(const ::mav_offboard::UpdateBoundOnlineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_offboard::UpdateBoundOnlineResponse> should match
// service_traits::DataType< ::mav_offboard::UpdateBoundOnline >
template<>
struct DataType< ::mav_offboard::UpdateBoundOnlineResponse>
{
  static const char* value()
  {
    return DataType< ::mav_offboard::UpdateBoundOnline >::value();
  }
  static const char* value(const ::mav_offboard::UpdateBoundOnlineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_OFFBOARD_MESSAGE_UPDATEBOUNDONLINE_H
