# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mav_offboard/MavOffbCtlType.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MavOffbCtlType(genpy.Message):
  _md5sum = "ecfa29034218f9eaa269cda4f3eba64a"
  _type = "mav_offboard/MavOffbCtlType"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
# mav offb control type for diff tasks
uint8 mav_offb_ctl_type

uint8 OFFBOARD_IGNORE = 0

uint8 GOTO_SETPOINT_STEP = 1
uint8 GOTO_SETPOINT_SMOOTH = 2

uint8 GOTO_SETPOINTS_STEP = 3
uint8 GOTO_SETPOINTS_SMOOTH = 4

uint8 POS_CTRL_BY_ATT = 5

uint8 POS_CTRL_BY_BODY_RATE = 6"""
  # Pseudo-constants
  OFFBOARD_IGNORE = 0
  GOTO_SETPOINT_STEP = 1
  GOTO_SETPOINT_SMOOTH = 2
  GOTO_SETPOINTS_STEP = 3
  GOTO_SETPOINTS_SMOOTH = 4
  POS_CTRL_BY_ATT = 5
  POS_CTRL_BY_BODY_RATE = 6

  __slots__ = ['mav_offb_ctl_type']
  _slot_types = ['uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mav_offb_ctl_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MavOffbCtlType, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mav_offb_ctl_type is None:
        self.mav_offb_ctl_type = 0
    else:
      self.mav_offb_ctl_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.mav_offb_ctl_type
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.mav_offb_ctl_type,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.mav_offb_ctl_type
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.mav_offb_ctl_type,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
